---
swagger: '2.0'
info:
  description: 'This specification describes the Otto event bus'
  version: '1.0.0'
  title: Otto Event Bus
  contact:
    email: 'rtyler@brokenco.de'
  license:
    name: 'GNU AGPL 3.0'
    url: 'https://www.gnu.org/licenses/agpl-3.0.en.html'
host: 'ottodeploys.us'
externalDocs:
  description: 'Find out more about Otto'
  url: 'https://github.com/rtyler/otto'
basePath: '/v1'
tags:
schemes:
- 'https'
- 'http'
paths:
  /channel:
    get:
      summary: 'List existing channels in the event bus'
      description: |
        Enumerate all the channels visible and available to the current client's permission scope
      operationId: 'listChannels'
      produces:
      - 'application/xml'
      - 'application/json'
      parameters:
      responses:
        200:
          description: 'Successful enumeration'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/Channel'
        400:
          description: 'Invalid request'
securityDefinitions:
definitions:
  Channel:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
      consumers:
        type: 'integer'
        description: 'Number of current consumers'
        format: 'int64'
      updatedAt:
        type: 'string'
        format: 'date-time'
      status:
        type: 'string'
        description: 'Channel Status'
        enum:
        - 'ready'
        - 'unavailable'
    xml:
      name: 'Channel'
