[workspace]

members = [
    "auctioneer",

    "agents/primitive",

    "eventbus",
    "eventbus-cli",
    "eventbus-inmemory",

    "processors/travis-ci",

    "osp",

    "stdlib/sh",
]

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
opt-level = "z"
