[package]
name = "otto-eventbus-cli"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
# Needed for the nice bits in the cli
rustyline = "~5.0.6"
tungstenite = "~0.11.0"
url = "~2.1.1"
