[package]
name = "otto-eventbus"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[[bin]]
name = "otto-eventbus"
path = "src/server/main.rs"

[dependencies]
async-std = "~1.4.0"
bastion = { "git" = "https://github.com/bastion-rs/bastion.git", branch = "master" }
tide = "~0.5.1"
mime = "~0.3.13"

num_cpus = "~1.11.1"

handlebars = "~2.0.2"
# Need to embed static resources into the binary for serving at runtime
rust-embed = { version = "~5.2.0", features = ["interpolate-folder-path"] }

# Used for formatting times in messages
chrono = "~0.4.10"

# Handling command line options
#clap = { version = "~2.33.0", features = ["yaml"] }
# Handling configuration overlays
config = { version = "~0.10.1", features = ["yaml"] }

# Logging
log = "~0.4.8"
pretty_env_logger = "~0.3.1"

# Adding the "rc" feature so we can serialize/deserialize Arc<T> and Rc<T>
serde = { version = "~1.0.104", features = ["rc"] }
serde_derive = "~1.0.104"
serde_json = "~1.0.0"
