[package]
name = "otto-eventbus"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "~0.9.0"
# Grabbing an alpha version with async/await support.
actix-web = "~2.0.0"
# This crate provides the websocket support which we will rely on for all
# clients
actix-web-actors = "~2.0.0"
actix-rt = "~1.0.0"
handlebars = "~2.0.2"
# Need to embed static resources into the binary for serving at runtime
rust-embed = "~5.2.0"

chrono = "~0.4.10"

# Logging
log = "~0.4.8"
pretty_env_logger = "~0.3.1"

serde = "~1.0.103"
serde_json = "~1.0.0"
