[package]
name = "eventbus"
version = "0.1.0"
authors = ["R. Tyler Croy <rtyler@brokenco.de>"]
edition = "2018"

[dependencies]
eventbus-api = { version = "1.0.0" , path = "../eventbus-api" }
chrono = { version = "0.4", features = ["serde"] }
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.2"
swagger = "0.12.1"
native-tls = {version = "0.1.4"}
openssl = {version = "0.9.14"}
tokio-proto = {version = "0.1.1"}
tokio-tls = {version = "0.1.3", features = ["tokio-proto"]}
clap = "2.25"
error-chain = "0.11"
